  # src/main/resources/application.yml
server:
  port: 3001

grpc:
  server:
    port: 9090

cors:
  domain: http://localhost/

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/chi_phuong
    username: root
    password: Thanh100%
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 1000ms

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    root: info
    org.springframework: info
  file:
    path: logs
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

jwt:
  secret: Y2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjYw==
  exp: 900000
  ref-exp: 604800000

rate-limit:
  limit: 100
  window-seconds: 60



